services:
  api:
    container_name: crypto-tracker
    image: crypto-tracker
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    cpus: 0.9
    volumes:
      - /logs/crypto-tracker:/usr/src/app/logs
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
  redis:
    container_name: redis
    image: redis:7.2-alpine
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - /private/var/lib/redis:/data
